service: elciess-aws-users

provider:
  name: aws
  runtime: nodejs20.x
  apiGateway:
    restApiId: 47dnuffm2f
    restApiRootResourceId: umzb4k6

plugins:
  - serverless-plugin-typescript
  - serverless-offline

package:
  individually: true

custom:
  serverless-plugin-typescript:
    tsconfig: ./tsconfig.json
  serverless-offline:
    httpPort: 3001

functions:
  createUser:
    handler: ./src/main/aws/aws-create-user.handler
    events:
      - http:
          path: /user/create
          method: post
          cors: true

  # authenticateUser:
  #   handler: ./src/handlers/authenticate-user.handler
  #   events:
  #     - http:
  #         path: /user/auth
  #         method: post
  #         cors: true
